import { useEffect, useMemo, useState, type FormEvent, type ReactElement } from 'react'
import { logout } from '../infrastructure/firebase/auth'
import { FirebaseIdentityAdapter, subscribeIdentity } from '../infrastructure/firebase/identityAdapter'
import { FirebaseSocialRepository } from '../infrastructure/firebase/socialRepository'
import type { AuthenticatedIdentity } from '../social/domain/identity'
import type { ActivityEvent, Post } from '../social/domain/models'

const identityAdapter = new FirebaseIdentityAdapter()
const repository = new FirebaseSocialRepository()
type Page = 'home' | 'post' | 'video' | 'profile'

export function SocialApp({ onDashboard }: { onDashboard: () => void }): ReactElement {
  const [identity, setIdentity] = useState<AuthenticatedIdentity | null>(() => identityAdapter.currentIdentity())
  const [page, setPage] = useState<Page>('home')
  const [posts, setPosts] = useState<Post[]>([])
  const [activity, setActivity] = useState<ActivityEvent[]>([])
  const [error, setError] = useState('')
  useEffect(() => subscribeIdentity(setIdentity), [])
  useEffect(() => { if (!identity) return; setError(''); const stopFeed = repository.subscribeHomeFeed(identity, setPosts, error => setError(error.message)); const stopActivity = repository.subscribeActivity(identity, setActivity, error => setError(error.message)); return () => { stopFeed(); stopActivity() } }, [identity])
  const recentActivity = useMemo(() => activity.filter(event => event.createdAtMs !== null).slice(0, 8), [activity])
  if (!identity) return <div className="loading">Waiting for authenticated identity…</div>
  async function handleLike(postId: string) { try { setError(''); await repository.likePost(identity!, postId) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Like failed') } }
  return <div className="social-shell"><header className="social-header"><button className="shortcut" onClick={() => setPage('home')}>📥 <span>Inbox</span></button><div className="social-title"><span className="brand-mark small">WD</span><strong>Social</strong></div><div className="header-actions"><button className="shortcut" onClick={() => setError('Activity is live from Firestore.')}>🔔</button><button className="shortcut" onClick={() => setError(`${recentActivity.length} recent activity event(s) loaded.`)}>❤️</button><button className="dashboard-button" onClick={onDashboard}>→ Dashboard</button></div></header><main className="social-main">{error && <div className="error banner">{error}</div>}{page === 'home' && <section className="feed-page"><div className="page-heading"><div><span className="eyebrow">REAL-TIME SOCIAL FEED</span><h1>Home</h1></div><span className="identity-pill">{identity.email}</span></div>{posts.length === 0 ? <div className="empty-state"><strong>No posts yet</strong><span>Your Home is empty because no persisted posts are available.</span></div> : posts.map(post => <article className="post-card" key={post.id}><div className="post-author"><div className="avatar">{post.authorEmail.slice(0, 1).toUpperCase()}</div><div><strong>{post.authorEmail}</strong><span>{post.createdAtMs ? new Date(post.createdAtMs).toLocaleString() : 'Publishing…'}</span></div></div><p>{post.content}</p><div className="interaction-bar"><button onClick={() => handleLike(post.id)}>❤️ {post.likeCount}</button><button>💬</button><button>↻</button><button>↗</button></div></article>)}</section>}{page === 'post' && <PostComposer identity={identity} onCreated={() => setPage('home')} />}{page === 'video' && <section className="empty-state"><strong>Video</strong><span>Video creation is the next Social vertical slice. No fake video UI is presented as functional.</span></section>}{page === 'profile' && <section className="profile-card"><div className="avatar large">{identity.email.slice(0, 1).toUpperCase()}</div><h1>{identity.email}</h1><p>Authenticated Social identity: {identity.userId}</p><p>This profile surface reads the authenticated identity directly.</p><button onClick={() => void logout()}>Sign out</button></section>}</main><nav className="bottom-nav"><button className={page === 'home' ? 'active' : ''} onClick={() => setPage('home')}>🏠<span>Home</span></button><button className={page === 'post' ? 'active' : ''} onClick={() => setPage('post')}>➕<span>Post</span></button><button className={page === 'video' ? 'active' : ''} onClick={() => setPage('video')}>🎬<span>Video</span></button><button className={page === 'profile' ? 'active' : ''} onClick={() => setPage('profile')}>🧑‍💼<span>Profile</span></button></nav></div>
}
function PostComposer({ identity, onCreated }: { identity: AuthenticatedIdentity; onCreated: () => void }): ReactElement { const [content, setContent] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); async function publish(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { await repository.createPost(identity, content); setContent(''); onCreated() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Post failed') } finally { setBusy(false) } } return <section className="composer-card"><span className="eyebrow">CREATE REAL POST</span><h1>Share something</h1><p>Published content is written to the authoritative Firestore datastore.</p><form onSubmit={publish}><textarea value={content} onChange={event => setContent(event.target.value)} maxLength={5000} required placeholder="Write your post…" />{error && <div className="error">{error}</div>}<button disabled={busy}>{busy ? 'Publishing…' : 'Publish'}</button></form></section> }
