import { useEffect, useState, type FormEvent, type ReactElement } from 'react'
import { WorkDiskSocialRepository } from '../infrastructure/workdisk/socialRepository'
import { FirebaseProfileRepository } from '../infrastructure/firebase/profileRepository'
import type { AuthenticatedIdentity } from '../social/domain/identity'
import type { ActivityEvent, Comment, Post, PostPrivacy, PostReaction } from '../social/domain/models'
import type { SocialProfile } from '../social/domain/profile'
import { REACTION_EMOJI, REACTION_OPTIONS } from '../social/domain/reactionCatalog'
import { ProfilePage } from './ProfilePage'
import './post-card.css'

const repository = new WorkDiskSocialRepository()
const profiles = new FirebaseProfileRepository()
type Page = 'home' | 'post' | 'video' | 'profile'

export function SocialApp({ identity, onDashboard }: { identity: AuthenticatedIdentity; onDashboard: () => void }): ReactElement {
  const [page, setPage] = useState<Page>('home')
  const [posts, setPosts] = useState<Post[]>([])
  const [activity, setActivity] = useState<ActivityEvent[]>([])
  const [error, setError] = useState('')

  useEffect(() => {
    const stopFeed = repository.subscribeHomeFeed(identity, setPosts, error => setError(error.message))
    const stopActivity = repository.subscribeActivity(identity, setActivity, error => setError(error.message))
    return () => { stopFeed(); stopActivity() }
  }, [identity])

  return <div className="social-shell">
    <header className="social-header">
      <button className="shortcut" onClick={() => setError('Inbox is not implemented yet.')}>📥 <span>Inbox</span></button>
      <div className="social-title"><span className="brand-mark small">WD</span><strong>Social</strong></div>
      <div className="header-actions">
        <button className="shortcut" onClick={() => setError(`Live activity events loaded: ${activity.length}.`)}>🔔</button>
        <button className="dashboard-button" onClick={onDashboard}>→ Dashboard</button>
      </div>
    </header>
    <main className="social-main">
      {error && <div className="error banner">{error}</div>}
      {page === 'home' && <section className="feed-page"><div className="page-heading"><div><span className="eyebrow">REAL-TIME SOCIAL FEED</span><h1>Home</h1></div></div>{posts.length === 0 ? <div className="empty-state"><strong>No posts yet</strong><span>Your Home is empty because no persisted posts are available.</span></div> : posts.map(post => <PostCard key={post.id} post={post} actor={identity} onError={setError} />)}</section>}
      {page === 'post' && <PostComposer identity={identity} onCreated={() => setPage('home')} />}
      {page === 'video' && <section className="empty-state"><strong>Video</strong><span>Video creation is the next Social vertical slice.</span></section>}
      {page === 'profile' && <ProfilePage identity={identity} />}
    </main>
    <nav className="bottom-nav"><button className={page === 'home' ? 'active' : ''} onClick={() => setPage('home')}>🏠<span>Home</span></button><button className={page === 'post' ? 'active' : ''} onClick={() => setPage('post')}>➕<span>Post</span></button><button className={page === 'video' ? 'active' : ''} onClick={() => setPage('video')}>🎬<span>Video</span></button><button className={page === 'profile' ? 'active' : ''} onClick={() => setPage('profile')}>🧑‍💼<span>Profile</span></button></nav>
  </div>
}

function ReactionPicker({ active, onSelect }: { active: PostReaction | null; onSelect: (reaction: PostReaction) => void }): ReactElement {
  return <div className="reaction-picker" role="menu" aria-label="Choose a reaction">{REACTION_OPTIONS.map(value => <button type="button" key={value} className={active === value ? 'active-reaction' : ''} aria-label={value} title={value} onClick={() => onSelect(value)}>{REACTION_EMOJI[value]}</button>)}</div>
}

function PostCard({ post, actor, onError }: { post: Post; actor: AuthenticatedIdentity; onError: (message: string) => void }): ReactElement {
  const [menuOpen, setMenuOpen] = useState(false); const [privacyOpen, setPrivacyOpen] = useState(false); const [reactionOpen, setReactionOpen] = useState(false); const [commentsOpen, setCommentsOpen] = useState(false); const [editing, setEditing] = useState(false); const [editText, setEditText] = useState(post.content); const [busy, setBusy] = useState(false); const [pressTimer, setPressTimer] = useState<number | null>(null)
  const authorName = post.author.profileName.trim() || 'Unknown user'; const authorPhoto = post.author.photoUrl.trim(); const timestamp = post.createdAtMs ? new Date(post.createdAtMs).toLocaleString() : 'Publishing…'; const own = post.authorId === actor.userId; const reactionCount = Object.values(post.reactionCounts).reduce((a, b) => a + b, 0)
  function beginLongPress() { setPressTimer(window.setTimeout(() => setReactionOpen(true), 500)) }; function endLongPress() { if (pressTimer !== null) window.clearTimeout(pressTimer); setPressTimer(null) }
  async function saveEdit() { setBusy(true); try { await repository.updatePost(actor, post.id, editText); setEditing(false) } catch (cause) { onError(cause instanceof Error ? cause.message : 'Edit failed') } finally { setBusy(false) } }
  async function deletePost() { if (!window.confirm('Delete this post?')) return; setBusy(true); try { await repository.deletePost(actor, post.id) } catch (cause) { onError(cause instanceof Error ? cause.message : 'Delete failed') } finally { setBusy(false); setMenuOpen(false) } }
  async function changePrivacy(value: PostPrivacy) { try { await repository.updatePostPrivacy(actor, post.id, value) } catch (cause) { onError(cause instanceof Error ? cause.message : 'Privacy update failed') } setPrivacyOpen(false); setMenuOpen(false) }
  async function react(value: PostReaction) { try { await repository.setPostReaction(actor, post.id, post.userReaction === value ? null : value) } catch (cause) { onError(cause instanceof Error ? cause.message : 'Reaction failed') } setReactionOpen(false) }
  async function share() { try { await repository.share(actor, post.id); const url = `${window.location.origin}/social/post/${post.id}`; if (navigator.share) await navigator.share({ title: authorName, text: post.content, url }); else await navigator.clipboard?.writeText(url) } catch (cause) { if (!(cause instanceof DOMException && cause.name === 'AbortError')) onError(cause instanceof Error ? cause.message : 'Share failed') } }
  return <article className="post-card"><div className="post-header"><div className="post-avatar">{authorPhoto ? <img src={authorPhoto} alt={authorName} /> : <span>{authorName.slice(0, 1).toUpperCase()}</span>}</div><div className="post-author-meta"><strong>{authorName}</strong><span>{timestamp} · {post.privacy === 'only_me' ? '🔒' : '🌐'}</span></div><div className="post-menu-wrap"><button className="post-menu" aria-label="Post options" onClick={() => setMenuOpen(value => !value)}>⋯</button>{menuOpen && own && <div className="post-menu-panel"><button onClick={() => { setEditing(true); setMenuOpen(false) }}>Edit</button><button onClick={deletePost}>Delete</button><button onClick={() => setPrivacyOpen(value => !value)}>Privacy →</button>{privacyOpen && <div className="privacy-panel"><button onClick={() => changePrivacy('public')}>Public</button><button onClick={() => changePrivacy('friends_followers')}>Friends &amp; Followers</button><button onClick={() => changePrivacy('selected_friends')}>Selected Friends</button><button onClick={() => changePrivacy('only_me')}>Only Me</button></div>}</div>}</div></div>{editing ? <div className="post-edit"><textarea value={editText} onChange={event => setEditText(event.target.value)} /><div><button onClick={saveEdit} disabled={busy}>{busy ? 'Saving…' : 'Save'}</button><button onClick={() => setEditing(false)}>Cancel</button></div></div> : <p>{post.content}</p>}<div className="interaction-bar"><div className="reaction-action"><button aria-haspopup="menu" aria-expanded={reactionOpen} onClick={() => setReactionOpen(value => !value)} onPointerDown={beginLongPress} onPointerUp={endLongPress} onPointerLeave={endLongPress}>{post.userReaction ? REACTION_EMOJI[post.userReaction] : '☺'} {reactionCount || ''}</button>{reactionOpen && <ReactionPicker active={post.userReaction} onSelect={react} />}</div><button onClick={() => setCommentsOpen(value => !value)}>💬 {post.commentCount || ''}</button><button onClick={share}>↗ Share</button></div>{commentsOpen && <CommentsPanel actor={actor} post={post} onError={onError} />}</article>
}

function CommentsPanel({ actor, post, onError }: { actor: AuthenticatedIdentity; post: Post; onError: (message: string) => void }): ReactElement {
  const [comments, setComments] = useState<Comment[]>([]); const [text, setText] = useState(''); const [replyTo, setReplyTo] = useState<string | null>(null); const [busy, setBusy] = useState(false)
  useEffect(() => repository.subscribeComments(actor, post.id, setComments, error => onError(error.message)), [actor, post.id, onError])
  async function addComment(event: FormEvent) { event.preventDefault(); if (!text.trim()) return; setBusy(true); try { await repository.createComment(actor, post.id, text, replyTo, extractMentions(text)); setText(''); setReplyTo(null) } catch (cause) { onError(cause instanceof Error ? cause.message : 'Comment failed') } finally { setBusy(false) } }
  return <section className="comments-panel"><strong>Comments</strong><div className="comments-list">{comments.map(comment => <CommentItem key={comment.id} comment={comment} actor={actor} postId={post.id} onReply={() => setReplyTo(comment.id)} onError={onError} />)}</div><form onSubmit={addComment} className="comment-form"><input value={text} onChange={event => setText(event.target.value)} placeholder={replyTo ? 'Write a reply…' : 'Write a comment…'} />{replyTo && <button type="button" onClick={() => setReplyTo(null)}>Cancel reply</button>}<button disabled={busy}>{busy ? 'Sending…' : replyTo ? 'Reply' : 'Comment'}</button></form></section>
}

function CommentItem({ comment, actor, postId, onReply, onError }: { comment: Comment; actor: AuthenticatedIdentity; postId: string; onReply: () => void; onError: (message: string) => void }): ReactElement { const [reactionOpen, setReactionOpen] = useState(false); const [editing, setEditing] = useState(false); const [text, setText] = useState(comment.content); const own = comment.authorId === actor.userId; const count = Object.values(comment.reactionCounts).reduce((a, b) => a + b, 0); async function react(value: PostReaction) { try { await repository.setCommentReaction(actor, postId, comment.id, comment.userReaction === value ? null : value) } catch (cause) { onError(cause instanceof Error ? cause.message : 'Comment reaction failed') } setReactionOpen(false) } async function save() { try { await repository.updateComment(actor, postId, comment.id, text, extractMentions(text)); setEditing(false) } catch (cause) { onError(cause instanceof Error ? cause.message : 'Comment edit failed') } } async function remove() { if (!window.confirm('Delete this comment?')) return; try { await repository.deleteComment(actor, postId, comment.id) } catch (cause) { onError(cause instanceof Error ? cause.message : 'Comment delete failed') } } return <div className={`comment-item ${comment.parentCommentId ? 'reply' : ''}`}><div className="post-avatar comment-avatar">{comment.author.photoUrl ? <img src={comment.author.photoUrl} alt={comment.author.profileName} /> : <span>{comment.author.profileName.slice(0, 1).toUpperCase()}</span>}</div><div className="comment-body"><strong>{comment.author.profileName}</strong>{editing ? <textarea value={text} onChange={event => setText(event.target.value)} /> : <p>{renderMentions(comment.content)}</p>}<small>{comment.createdAtMs ? new Date(comment.createdAtMs).toLocaleString() : ''}{comment.editedAtMs ? ' · edited' : ''}</small><div className="comment-actions"><div className="reaction-action"><button aria-haspopup="menu" aria-expanded={reactionOpen} onClick={() => setReactionOpen(value => !value)}>{comment.userReaction ? REACTION_EMOJI[comment.userReaction] : '☺'} {count || ''}</button>{reactionOpen && <ReactionPicker active={comment.userReaction} onSelect={react} />}</div><button onClick={onReply}>Reply</button>{own && !editing && <><button onClick={() => setEditing(true)}>Edit</button><button onClick={remove}>Delete</button></>}{editing && <><button onClick={save}>Save</button><button onClick={() => setEditing(false)}>Cancel</button></>}</div></div></div> }
function extractMentions(value: string): string[] { return [...value.matchAll(/@([A-Za-z0-9._-]+)/g)].map(match => match[1]).filter(Boolean) }
function renderMentions(value: string): ReactElement { return <>{value.split(/(@[A-Za-z0-9._-]+)/g).map((part, index) => part.startsWith('@') ? <strong key={index} className="mention">{part}</strong> : part)}</> }

function PostComposer({ identity, onCreated }: { identity: AuthenticatedIdentity; onCreated: () => void }): ReactElement { const [content, setContent] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [profile, setProfile] = useState<SocialProfile | null>(null); const [privacy, setPrivacy] = useState<PostPrivacy>('public'); useEffect(() => { void profiles.getProfile(identity).then(setProfile).catch(cause => setError(cause instanceof Error ? cause.message : 'Profile failed')) }, [identity]); async function publish(event: FormEvent) { event.preventDefault(); if (!content.trim()) return; setBusy(true); setError(''); try { await repository.createPost(identity, content, privacy, [], extractMentions(content)); setContent(''); onCreated() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Post failed') } finally { setBusy(false) } } return <section className="composer-card"><span className="eyebrow">CREATE REAL POST</span><h1>Share something</h1>{profile && <div className="post-composer-identity"><div className="post-avatar">{profile.photoUrl ? <img src={profile.photoUrl} alt={profile.profileName} /> : <span>{profile.profileName.slice(0, 1).toUpperCase()}</span>}</div><strong>{profile.profileName}</strong></div>}<form onSubmit={publish}><textarea value={content} onChange={event => setContent(event.target.value)} maxLength={5000} required placeholder="Write your post… Use @name to mention someone." /><select value={privacy} onChange={event => setPrivacy(event.target.value as PostPrivacy)}><option value="public">Public</option><option value="friends_followers">Friends &amp; Followers</option><option value="selected_friends">Selected Friends</option><option value="only_me">Only Me</option></select>{error && <div className="error">{error}</div>}<button disabled={busy}>{busy ? 'Publishing…' : 'Publish'}</button></form></section> }
