import type { ActivityEvent, Comment, Post, PostPrivacy, PostReaction } from '../../social/domain/models'
import type { AuthenticatedIdentity } from '../../social/domain/identity'
import type { SocialRepositoryPort } from '../../social/application/ports'
import { validatePostContent } from '../../social/domain/validation'

const baseUrl = (import.meta.env.VITE_WORK_DISK_SOCIAL_API_URL || 'http://localhost:8787').replace(/\/$/, '')
type ApiPost={id:string;authorId:string;wdId:string;profileName:string;photoUrl:string;content:string;privacy:PostPrivacy;createdAtMs:number;editedAtMs?:number}
type ApiComment={id:string;postId:string;authorId:string;wdId:string;profileName:string;photoUrl:string;content:string;parentCommentId:string|null;mentions:string;createdAtMs:number;editedAtMs?:number}
async function request<T>(identity:AuthenticatedIdentity,path:string,init:RequestInit={}):Promise<T>{const headers=new Headers(init.headers);headers.set('Content-Type','application/json');headers.set('X-Work-Disk-User',identity.userId);const response=await fetch(`${baseUrl}${path}`,{...init,headers});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error?.message||`Work_Disk Social request failed (${response.status})`);return body as T}
function profileSnapshot(actor:AuthenticatedIdentity){return{wdId:localStorage.getItem(`wd.profile.${actor.userId}.id`)||actor.userId,profileName:localStorage.getItem(`wd.profile.${actor.userId}.name`)||'',photoUrl:localStorage.getItem(`wd.profile.${actor.userId}.photo`)||''}}
function postFromApi(v:ApiPost):Post{return{id:v.id,authorId:v.authorId,author:{wdId:v.wdId,profileName:v.profileName,photoUrl:v.photoUrl},content:v.content,createdAtMs:v.createdAtMs,likeCount:0,privacy:v.privacy,reactionCounts:{} as Record<PostReaction,number>,userReaction:null,commentCount:0,repostCount:0}}
function commentFromApi(v:ApiComment):Comment{return{id:v.id,postId:v.postId,authorId:v.authorId,author:{wdId:v.wdId,profileName:v.profileName,photoUrl:v.photoUrl},content:v.content,parentCommentId:v.parentCommentId,createdAtMs:v.createdAtMs,editedAtMs:v.editedAtMs||null,likeCount:0,reactionCounts:{} as Record<PostReaction,number>,userReaction:null,mentions:v.mentions?v.mentions.split(',').filter(Boolean):[]}}
export class WorkDiskSocialRepository implements SocialRepositoryPort{
 async createPost(actor:AuthenticatedIdentity,content:string,privacy:PostPrivacy='public',taggedUserIds:string[]=[],mentions:string[]=[]):Promise<Post>{const p=profileSnapshot(actor);const clean=validatePostContent(content);if(!p.profileName.trim())throw new Error('PROFILE_REQUIRED: Work_Disk profile name is required before posting');const r=await request<{id:string;createdAtMs:number}>(actor,'/api/v1/social/posts',{method:'POST',body:JSON.stringify({actorId:actor.userId,...p,content:clean,privacy,taggedUserIds,mentions:mentions.join(','),selectedUserIds:privacy==='selected_friends'?taggedUserIds.join(','):''})});return{id:r.id,authorId:actor.userId,author:p,content:clean,createdAtMs:r.createdAtMs,likeCount:0,privacy,reactionCounts:{} as Record<PostReaction,number>,userReaction:null,commentCount:0,repostCount:0}}
 subscribeHomeFeed(actor:AuthenticatedIdentity,onChange:(posts:Post[])=>void,onError:(error:Error)=>void):()=>void{let stopped=false;const load=async()=>{try{const r=await request<ApiPost[]>(actor,'/api/v1/social/feed');if(!stopped)onChange(r.map(postFromApi))}catch(e){if(!stopped)onError(e instanceof Error?e:new Error('Feed request failed'))}};void load();const timer=window.setInterval(load,3000);return()=>{stopped=true;window.clearInterval(timer)}}
 async updatePost(actor:AuthenticatedIdentity,id:string,content:string){await request(actor,`/api/v1/social/posts/${id}`,{method:'PATCH',body:JSON.stringify({content:validatePostContent(content)})})}
 async deletePost(actor:AuthenticatedIdentity,id:string){await request(actor,`/api/v1/social/posts/${id}`,{method:'DELETE'})}
 async updatePostPrivacy(actor:AuthenticatedIdentity,id:string,privacy:PostPrivacy,selected:string[]=[]){await request(actor,`/api/v1/social/posts/${id}`,{method:'PATCH',body:JSON.stringify({privacy,selectedUserIds:selected.join(',')})})}
 async setPostReaction(actor:AuthenticatedIdentity,id:string,reaction:PostReaction|null){await request(actor,`/api/v1/social/posts/${id}/reactions`,{method:'POST',body:JSON.stringify({reaction:reaction||''})})}
 subscribeComments(actor:AuthenticatedIdentity,postId:string,onChange:(comments:Comment[])=>void,onError:(error:Error)=>void):()=>void{let stopped=false;const load=async()=>{try{const r=await request<ApiComment[]>(actor,`/api/v1/social/posts/${postId}/comments`);if(!stopped)onChange(r.map(commentFromApi))}catch(e){if(!stopped)onError(e instanceof Error?e:new Error('Comments request failed'))}};void load();const timer=window.setInterval(load,3000);return()=>{stopped=true;window.clearInterval(timer)}}
 async createComment(actor:AuthenticatedIdentity,postId:string,content:string,parentCommentId:string|null=null,mentions:string[]=[]):Promise<Comment>{const p=profileSnapshot(actor);const r=await request<{id:string}>(actor,`/api/v1/social/posts/${postId}/comments`,{method:'POST',body:JSON.stringify({...p,content,parentCommentId,mentions:mentions.join(',')})});return{id:r.id,postId,authorId:actor.userId,author:p,content,parentCommentId,createdAtMs:Date.now(),editedAtMs:null,likeCount:0,reactionCounts:{} as Record<PostReaction,number>,userReaction:null,mentions}}
 async updateComment(actor:AuthenticatedIdentity,postId:string,id:string,content:string,mentions:string[]=[]){await request(actor,`/api/v1/social/posts/${postId}/comments/${id}`,{method:'PATCH',body:JSON.stringify({content,mentions:mentions.join(',')})})}
 async deleteComment(actor:AuthenticatedIdentity,postId:string,id:string){await request(actor,`/api/v1/social/posts/${postId}/comments/${id}`,{method:'DELETE'})}
 async setCommentReaction(actor:AuthenticatedIdentity,postId:string,id:string,reaction:PostReaction|null){await request(actor,`/api/v1/social/posts/${postId}/comments/${id}/reactions`,{method:'POST',body:JSON.stringify({reaction:reaction||''})})}
 async share(actor:AuthenticatedIdentity,postId:string){await request(actor,`/api/v1/social/posts/${postId}/share`,{method:'POST',body:JSON.stringify({destination:'external'})})}
 async likePost(actor:AuthenticatedIdentity,id:string){await this.setPostReaction(actor,id,'like')}
 subscribeActivity(_actor:AuthenticatedIdentity,onChange:(events:ActivityEvent[])=>void){onChange([]);return()=>{}}
}
